### ISSUE TITLE
How to update this template to use pnpm instead npm?

### ISSUE THREAD

**Issue by isantiago95** [AlbertHernandez/nestjs-service-template#259]
# Prerequisites

- [x ] I checked the documentation and found no answer

**Is your feature request related to a problem? Please describe.**
This template was build with npm, but what if we use pnpm?

**Describe the solution you'd like**
Run everything as usual, except the installation of dependencies that should be with `pnpm install`, this will cause the creation of `pnpm-lock.yaml` file, which should be the one taken to build the image in docker.

**Comment by AlbertHernandez** [comment]
Hey @isantiago95, I know `pnpm` is a great alternative to `npm` but from now I prefer to use `npm` in the template. In case you want to use the other solution it should be as much as simple as delete current `package-lock.json`, change the scripts from use `npm` to `pnpm` and generate the lock with the `pnpm install`. Maybe at some point I will change it to `pnpm` or other package manager but not from now

**Comment by AlbertHernandez** [comment]
Closing this issue since is not going to be implemented from now
